#!/usr/bin/env bash
# Bash Script Loops 1-20, echoes specific messages for 4th, 9th, and 17th iteration, else echoes count.
count=1

while [[ $count -le 20 ]]; do
  case $count in
    4)
      echo "4, bad luck from China"
      ;;
    9)
      echo "9, bad luck from Japan"
      ;;
    17)
      echo "17, bad luck from Italy"
      ;;
    *)
      echo "$count"
      ;;
  esac

  count=$((count + 1))
done
