#!/usr/bin/env bash
# This scrip displays The content of the current directory with extra details
for file in *-*; do  # Loop through files matching the pattern "*-*"
  filename="${file##*-}"  # Extract part of the filename after the first "-"
  echo "$filename"
done
